### ISSUE TITLE
Insertion sort using java

### ISSUE THREAD

**Issue by Starplayevryr** [strivedi4u/hacktoberfest2024#186]
Fixes #185

**Comment by VanshDobhal** [comment]
hello i would like to work on this please assign it to me

**Comment by Ruchika2005** [comment]
Hi , I am Ruchika Patil. Could you please assign this issue to me ?

**Comment by Sanskruti36** [comment]
Hi , I am Sanskruti Patil. Could you please assign this issue to me ?
