### ISSUE TITLE
Algorthimic approach to sum the squares of numbers in an array without using any loops.

### ISSUE THREAD

**Issue by Nikhil1601** [strivedi4u/hacktoberfest2024#229]
An algorithm in python that can calculate the sum of squares of number in an array without using any for or while loops. The basic premise is to enhance the understanding of recursion workflow.

Please assign me this issue and add Hacktoberfest 2024 label.

**Comment by harshitajha4680** [comment]
I'm interested, please assign this to me!

**Comment by guptushar27** [comment]
please assign this to me!
