### ISSUE TITLE
Age Calculator 

### ISSUE THREAD

**Issue by ArisuAbhilash** [strivedi4u/hacktoberfest2024#61]
An app that calculates the user's age based on their date of birth and the current date.

Features:
Input date of birth and calculate the exact age (years, months, days).
Could include optional features like the time until the next birthday.
Tech Stack: JavaScript (for date calculations), Flask (for backend processing).

**Please assign me this task under hacktoberfest 2024**

**Comment by Abhijit-codder** [comment]
please assign me this task as I would like to make contribution to this project
