### ISSUE TITLE
Find All Anagrams in a String

### ISSUE THREAD

**Issue by Astordnomer** [strivedi4u/hacktoberfest2024#88]
Can You Assign Me

**Comment by w0wayush** [comment]
Can I work on this ??

**Comment by w0wayush** [comment]
I have completed the task and created a PR #133 containing the code for it.

**Comment by Shrutika-TechSavvy** [comment]
Hey @strivedi4u , Please assign me this under the Hacktoberfest2024 tag. I will provide the optimized code in Java for this. It's my first time for contribution.
Eager to contribute!!!!!!!!!!!
