### ISSUE TITLE
Longest Increasing subsequence using binary search most optimal approach

### ISSUE THREAD

**Issue by namanmodi65** [strivedi4u/hacktoberfest2024#99]
Hey can you assign me the task of Implement the Longest Increasing Subsequence (LIS) using the binary search approach in C++ as part of Hacktoberfest 2024. Provide a detailed explanation of the algorithm and compare its efficiency with other approaches like the dynamic programming solution.

**Comment by strivedi4u** [comment]
🚀 Follow me, 💬 Join the WhatsApp Group, and ⭐ Star the Repo to support our journey together!

**Comment by namanmodi65** [comment]
Done
